version: '2.2'
services:
  backend:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.prod
    image: momigteam/momig-backend #-dev
    volumes:
      - ./sample/chm1:/vg/static
    ports: 
      - "8081:8081"
    init: true
