version: '2.2'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: momig/momig-backend-dev
    volumes:
      - ./sample/chromothripsis:/vg/static
    ports: 
      - "8081:8081"
    init: true
