bin:
  vg: "vg"
  vg_tmp: "vg"
  vg_volume_prefix: ""
  graphviz: "dot"
  fa22bit: "faToTwoBit"
  bigbed: "bedToBigBed"
reference:
  chroms: "static/GRCh.json"
  data:
    - name: "hg19"
      features:
        - name: 'gene_annotation'
          url: "static/gencode.v27lift37.basic.annotation.gff3"
          chr_prefix: "chr"
    - name: "hg38"
      features:
        - name: 'gene_annotation'
          url: "static/gencode.v27.basic.annotation.gff3"
          chr_prefix: "chr"
data:
  - name: "chm1"
    desc: "2017/12/18"
    chr_prefix: ""
    ref_id: "hg38"
    source: 
#      xg: "static/chm1_chr21.xg"
      xg: "static/grch38_na12878_gencode_paths_sort.xg"
      csv: "static/chm1_chr21.pcf"
      gam: "static/t.gam"
      gamindex: "static/t.gam.index"
    features: []
    static_files: []
